server:
  port: 8181
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-jasper #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
